filter:
  year: 2015
  max_num_rows_read: 1000000
  chunksize: 10000
  log_per_chunks: 10
clean:
  clean_fare_amount:
    initial_charge: 2.5
  clean_locations:
    nyc_min_lon: -75
    nyc_max_lon: -72
    nyc_min_lat: 39
    nyc_max_lat: 42
  clean_passenger_count:
    min_count: 1
    max_count: 5
featurize:
  generate_hour:
    generate: True
  generate_dayofweek:
    generate: True
  generate_distance:
    generate: True
split:
  stratified_sampling:
    strata_cols:
      - pickup_hour
      - pickup_dayofweek
    sample_obs: 10000
    test_size: 0.3
    random_state: 678
  one_hot_encoder:
    one_hot_dict:
      pickup_dayofweek:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
      pickup_hour:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
train:
  target_column: fare_amount
  n_estimators: 500
  min_samples_split: 5
  random_state: 678
score:
  target_column: fare_amount
evaluate:
  y_test_name: y_test
  ypred_name: ypred_test

